force-app/main/default/objects/Gift__c/Gift__c.object-meta.xml
<CustomObject>
    <label>Gift</label>
    <nameField>
        <label>Gift Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gifts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Gift__c/fields/From__c.field-meta.xml
<CustomField>
    <fullName>From__c</fullName>
    <label>From</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Gift__c/fields/Gift_Exchange__c.field-meta.xml
<CustomField>
    <fullName>Gift_Exchange__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Gift Exchange</label>
    <referenceTo>Gift_Exchange__c</referenceTo>
    <relationshipLabel>Gifts</relationshipLabel>
    <relationshipName>Gifts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Gift__c/fields/Opened__c.field-meta.xml
<CustomField>
    <fullName>Opened__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Opened</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Gift__c/fields/Recipient__c.field-meta.xml
<CustomField>
    <fullName>Recipient__c</fullName>
    <label>Recipient</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Gift__c/fields/Wrapped_URL__c.field-meta.xml
<CustomField>
    <fullName>Wrapped_URL__c</fullName>
    <defaultValue>&quot;/resource/Presents/Presents/&quot; &amp;  right(text(TimeNOW()), 1)  &amp; &quot;.png&quot;</defaultValue>
    <label>Wrapped URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Gift_Exchange__c/Gift_Exchange__c.object-meta.xml
<CustomObject>
    <label>Gift Exchange</label>
    <nameField>
        <label>Gift Exchange ame</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gift Exchanges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/GiftController.cls
public with sharing class GiftController {
    public GiftController() {

    }

    @AuraEnabled(cacheable=true)
    public static List<Gift__c> getAllGifts() {
        return [
            SELECT Name, Id, From__c, Image_URL__c, Recipient__c, Wrapped_URL__c, Opened__c
            FROM Gift__c
        ];
    }

    @AuraEnabled(cacheable=true)
    public static List<Gift__c> getGiftsByExchangeId(String id) {
        return [
            SELECT Name, Id, From__c, Image_URL__c, Recipient__c, Wrapped_URL__c, Opened__c
            FROM Gift__c where Gift_Exchange__c =: id
        ];
    }

    @AuraEnabled(cacheable=true)
    public static List<Gift_Exchange__c> getExchangeNames() {
        return [
            SELECT Name, Id
            FROM Gift_Exchange__c WHERE Active__c = true
        ];
    }

    @AuraEnabled
    public static void openGift(String recordId) {
        Gift__c openedGift = new Gift__c();
        openedGift.id = recordId;
        openedGift.Opened__c = true;
        update openedGift;

        return ;
    }

    @AuraEnabled
    public static String getRecipient(String recordId) {
        String recipient = 'bob';
       Gift__c item = [ SELECT Id, Recipient__c
        FROM Gift__c where id =: recordId];
        return item.Recipient__c;
    }
}